### ISSUE TITLE
Timeline/requirements for Ledger integration

### ISSUE THREAD

**Issue by Z2z123** [Zondax/ledger-zcash#30]
Hi, are we still waiting on Ledger to integrate this? Is there a way to speed up the process such as if a desktop wallet supported the app?
Would much work be required to support Orchard/Unified addresses? I would say a grant from ZF or ZOMG would be easily supported once Sapling's running on Ledger. 
Cheers 

:link: [zboto Link](https://app.clickup.com/t/2k59aaz)

**Comment by jleni** [comment]
The problem is that nobody integrated the app in a web or desktop wallet and this was beyond our scope.

We have been discussing with ZF or ZOMG that we could actually integrate ourselves or even create a new wallet.

Without any integration of our app into a wallet, Ledger will never release.

**Comment by jleni** [comment]
This app has been getting old and needs also some maintenance as this stage:
- Upgrade SDKs
- support orchard, etc.

We really put a lot of effort to get this working in Nano S. Actually, it was more like a challenge and a contribution to the community rather than something economically efficient. So we would also love this see this app in the wild being used by people!

**Comment by luckytokidoki** [comment]
https://zcashcommunitygrants.org/ would welcome any proposal to get this in the hands of user.

Btw any reason why [issue 21](https://github.com/Zondax/ledger-zcash/issues/21) was completely ignored?

**Comment by jleni** [comment]
It has not been ignored, however, it is difficult for us to justify continuous attention and support of this app after so much time since the completion of our milestones (years?). 

In the original discussion, we suggested and preferred to be in charge of the integration to be 100% we had control over that timeline too. 

Thanks for your suggestion, we will definitely reach out and see how we can reboot this project. This means upgrading the project and taking over integration work so we can ensure that the project gets to users.

**Comment by luckytokidoki** [comment]
If you're serious about getting this into the hands of end-users, submit a [Zcash Community Grants](https://zcashcommunitygrants.org/) and [respond to the community feedback on the forum](https://forum.zcashcommunity.com/t/40247/). Don't be surprised that people are disappointed with you folks when there has been no update whatsoever for so long on this project.

**Comment by hhanh00** [comment]
Hi @jleni, I have given a good effort to make this app run but unfortunately I have now run into a wall. The app cannot load anymore after a firmware upgrade. It seems to be just missing some small things. 

Great work, it was clearly quite challenging.

**Comment by hhanh00** [comment]
FYI, I managed to use integrate it in Ywallet --> https://www.youtube.com/watch?v=IazybvQg68w

**Comment by jleni** [comment]
Moreover, I hope you can see that we handled some the changes here:

> This app has been getting old and needs also some maintenance as this stage:
> 
> Upgrade SDKs
> support orchard, etc.
> We really put a lot of effort to get this working in Nano S. Actually, it was more like a challenge and a contribution to the community rather than something economically efficient. So we would also love this see this app in the wild being used by people!
