### ISSUE TITLE
App hangs / cannot be loaded

### ISSUE THREAD

**Issue by hhanh00** [Zondax/ledger-zcash#45]
On the nano s, latest firmware, the app:
- v3. cannot be loaded -> `ledgerblue.commException.CommException: Exception : Invalid status 5103`
- v2. can be loaded but hangs when opened

Previous firmware could run v2. Unfortunately, I cannot downgrade and I'm stuck now with no working version.

App works fine in zemu

:link: [zboto Link](https://app.clickup.com/t/2k59a94)

**Comment by jleni** [comment]
We are reactivating development in this app... So it will get a tiny bit unstable because it is very memory sensitive.. but it should go back to normal in 1 or 2 weeks. 
Happy to see you are following the development!! It is not a normal app.. quite complex to get this to work in such small device..

**Comment by hhanh00** [comment]
I see you released a new build but I can't seem to load it on my nano s either.

**Comment by jleni** [comment]
I think this is not relevant anymore, can you confirm @hhanh00 ?

**Comment by hhanh00** [comment]
Unfortunately, I still get the same error. Building and loading the bitcoin-test app works flawlessly but not this one.

**Comment by jleni** [comment]
It is probably related to app size and available space in the device.

Ledger modified the error codes in firmware 2.0 and I believe 5103 is related to size.

@ftheirs @becominginsane  maybe you can confirm?

**Comment by hhanh00** [comment]
FYI, my nano S is freshly reset and does not contain any app, yet it cannot load this app.

**Comment by becominginsane** [comment]
5103 should be indeed related to size.
I wasn't able to load the app on my clean Nano S either, with that error being thrown. I had observed it in the past and we had confirmation from ledger that it's related to insufficient space

**Comment by becominginsane** [comment]
The app has increased in size overtime solely via the Ledger SDK to the current status where it doesn't fit in a Nano S device anymore. 
Considering that [Ledger discontinued the Nano S device](https://twitter.com/Ledger/status/1542148745172762626?s=20&t=HbGIqdYIRdXJPs6VmCWNNQ), all support moving forward will be for the Nano X and S+ devices only.

**Comment by becominginsane** [comment]
Hey @hhanh00 we are trying to do some integration & update work and we already noticed you [integrated the app](https://www.youtube.com/watch?v=IazybvQg68w) with YWallet... 
Does this code live somewhere? Can we access it to test our changes since you have a working integration already? Also we'd like to have a channel to communicate with you, can you reach out to francesco <at> zondax.ch ? 

Thank you!

**Comment by hhanh00** [comment]
The code is on github https://github.com/hhanh00/zcash-sync/blob/master/src/ledger/sapling.rs

Note that it is experimental and not in production.

**Comment by hhanh00** [comment]
@becominginsane i have sent an email to Francesco.
